# Week 1  

In [2]:
import numpy as np

In [4]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [58]:
a.T

array([1, 2, 3, 4])

In [59]:
a == a.T

array([ True,  True,  True,  True])

In [9]:
b = np.arange(5, 9)
b

array([5, 6, 7, 8])

`Dot product`

In [10]:
np.dot(a, b)

70

In [11]:
a.dot(b)

70

In [60]:
a.dot(a)

30

In [61]:
a.dot(a.T)

30

In [62]:
np.dot(a.T, b.T)

70

`Hadamard product`  

In [12]:
a*b

array([ 5, 12, 21, 32])

`Vector multiplication`  

In [13]:
a @ b

70

In [16]:
a.dot(b) == np.dot(a, b) == a @ b

True

`Addition`  

In [45]:
a + 31

array([32, 33, 34, 35])

In [46]:
b + 21

array([26, 27, 28, 29])

In [47]:
a + b

array([ 6,  8, 10, 12])

In [48]:
a + b + 101

array([107, 109, 111, 113])

In [49]:
a.T + b.T

array([ 6,  8, 10, 12])

# Week 2  

`PPA 1`  

In [66]:
def add_one(X):
    return np.column_stack((np.ones(len(X)), X))
    

In [73]:
X = np.arange(1, 5)
add_one(X)

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.]])

`PPA 2`  

In [69]:
def multiply(X, w):
    X = np.column_stack((np.ones(len(X)), X))
    if X.shape[1] == w.shape[0]:
        return X @ w
    return None

In [74]:
X = np.arange(1, 5)
w = np.array([5, 7])
multiply(X, w)

array([12., 19., 26., 33.])

`PPA 3`  

In [83]:
def loss(X, w , y):
    X = np.column_stack((np.ones(len(X)), X))
    if X.shape[1] == w.shape[0]:
        y_pred = X @ w
    return np.sum((y - y_pred)**2)

In [84]:
X = np.arange(1, 5)
w = np.array([5, 7])
y = np.array([14, 17, 27, 33])

# loss(X, y, w) # Should return error

loss(X, w, y)   # Should return correct answer (9.0)

9.0

In [89]:
# Alternate method  
def loss2(X, w , y):
    X = np.column_stack((np.ones(len(X)), X))
    if X.shape[1] == w.shape[0]:
        e = (X @ w) - y     # 'e' is error vector
    return e.T @ e

In [90]:
X = np.arange(1, 5)
w = np.array([5, 7])
y = np.array([14, 17, 27, 33])

# loss(X, y, w) # Should return error

loss2(X, w, y)   # Should return correct answer (9.0)

9.0

`GrPA 1`  

In [121]:
def compatibility(X, w):
    if X.shape[-1] == w.shape[0]:
        return "Compatible"
    return "Not compatible"

In [122]:
X = np.arange(1, 5)
w = np.array([5, 7])

print(X.shape, w.shape)
print(compatibility(X, w))

(4,) (2,)
Not compatible


In [123]:
X2 = np.column_stack((np.ones(len(X)), X))
w = np.array([5, 7])

print(X2.shape, w.shape)
print(compatibility(X2, w))

(4, 2) (2,)
Compatible


`GrPA 2`  

In [126]:
def gradient(X, w , y):
    X = np.column_stack((np.ones(len(X)), X))
    if X.shape[1] == w.shape[0]:
        grad = X.T @ ((X @ w) - y)
        return grad
    return None

In [127]:
X = np.arange(1, 5)
w = np.array([5, 7])
y = np.array([14, 17, 27, 33])

gradient(X, w, y)

array([-1., -1.])

`GrPA 3`  

In [128]:
def weight_update(X, w, y, lr):
    X = np.column_stack((np.ones(len(X)), X))
    if X.shape[1] == w.shape[0]:
        e = (X @ w) - y
        grad = X.T @ e
        return (w - lr*grad)
    return None

In [134]:
X = np.arange(1, 5)
w = np.array([5, 7])
y = np.array([14, 17, 27, 33])

gradient(X, w, y)

lr = 0.1
print(f"Original weight vector: {w}")
print(f"Updated weight vector: {weight_update(X, w, y, lr)}")

Original weight vector: [5 7]
Updated weight vector: [5.1 7.1]


# Week 4  