# Week 3  

`PPA1`   

In [1]:
import numpy as np
import random
import itertools
import functools

In [4]:
def get_combinations(x, degree):
    return itertools.combinations_with_replacement(x, degree)

def compute_new_features(items):
    return functools.reduce(lambda x, y: x*y, items)

def polynomial_transform(x, degree):
    if x.ndim == 1:
        x = x[:, None]
    
    x_t = np.transpose(x)
    features = [np.ones(len(x))]

    for deg in range(1, degree+1):
        for items in get_combinations(x_t, degree):
            features.append(compute_new_features(items))

    polynomial_feature_matrix = np.asarray(features).transpose()
    return polynomial_feature_matrix

`PPA2`  

In [6]:
def ridge_loss(X, w, y, lr):
    X = np.column_stack((np.ones(X.shape[0]), X))
    e = (X @ w) - y
    loss = (1/2) * (e.T @ e)  + (lr/2) * (w.T @ w)
    return loss

# Remember to check compatibility between X, w and y, if needed.  

`GrPA1`  

Use the function `polynomial_transform` along with it's two helper functions defined in `PPA1`.  

In [8]:
def model_error(X, y, degree):
    X_poly = polynomial_transform(X, degree)
    w = np.linalg.pinv(X_poly) @ y
    e = (X @ w) - y
    mse = np.mean((e.T @ e))
    rmse = np.sqrt(mse)
    return rmse

`GrPA2`  

In [9]:
def additional_vector(X):
    n = X.shape[0]
    weird_col = np.ndarray([0 if i%2 == 0 else 1 for i in range(n)])
    return np.column_stack((X, weird_col))

`GrPA3`  

In [11]:
import numpy as np
import random
def mean_abs(X, y, w):
    y_hat = X @ w
    return np.mean(np.abs((y - y_hat)))

# Remember to check compatibility between X, w and y, if needed.  

In [12]:
import numpy as np
import random
def mean_abs(X,y,w):
  e = ((X @ w) - y)
  return sum([abs(i) for i in e]) / (len(e))

# Remember to check compatibility between X, w and y, if needed.  

# Week 4  

`PPA`  
pending

`GrPA1`  

In [13]:
import numpy as np
def OneHotEncode(y):
    k = np.max(y) + 1
    M = np.eye(k)
    return M[y]

In [14]:
y = np.array([[0, 2, 1, 3, 3, 2, 1, 0, 1, 2]])
OneHotEncode(y)

array([[[1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]])

In [20]:
k = np.max(y) + 1
np.eye(k)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
z = np.array([[3,2,1]])
np.eye(k)[z]

array([[[0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.]]])

`GrPA2`  

In [24]:
import numpy as np
def update(x, w, y, epochs):
    hist = []
    wi = np.zeros(x.shape[1])
    hist.append(wi)
    wi = w
    for i in range(epochs):
        for xi, yi in zip(x, y):
            y_hat = np.where((xi@wi) >= 0, 1, -1)
            wi = wi + 1 * (yi - y_hat) * xi
        hist.append(wi)

    return hist

`GrPA3`  

In [ ]:
import numpy as np
def is_linearly_separable(X, y):
    e = []
    w = np.zeros(X.shape[1])
    for i in range(10):
        err = 0
        for xi, yi in zip(X, y):
            y_hat = np.where((xi@w) >= 0, 1, -1)
            w += (yi - y_hat) * xi
            err += max(0, -1*(xi@w)*yi)
        e.append(err)
    if e[-1] == 0:
        return True
    return False