## Q3 GA5

In [2]:
X = np.array([[1, 2], [1, 3]])
y = np.array([1, 0])
w = np.array([0.1, 0.2])
print(X.shape)
print(y.shape)
print(w.shape)

(2, 2)
(2,)
(2,)


In [3]:
class LogisticRegression(object):
  def set_weight_vector(self, w):
    self.w = w

  def linear_combination(self, X:np.ndarray) -> np.ndarray:
    return X @ self.w

  def sigmoid(self, z:np.ndarray) -> np.ndarray:
    return 1/(1 + np.exp(-z))

  def activation(self, X:np.ndarray) -> np.ndarray:
    return self.sigmoid(self.linear_combination(X))

  def predict(self, x:np.ndarray, threshold:float = 0.5):
    return (self.activation(x) > threshold).astype(int)

  def loss(self, X:np.ndarray, y:np.ndarray, reg_rate:float) -> float:
    predicted_prob = self.activation(X)
    return (-1 * (np.sum(y * np.log(predicted_prob) + (1-y) * np.log(1-predicted_prob))) +
    reg_rate * np.dot(np.transpose(self.w), self.w))

  def calculate_gradient(self, X:np.ndarray, y:np.ndarray, reg_rate:float) -> np.ndarray:
    return np.transpose(X) @ (self.activation(X) - y) + reg_rate * self.w

  def update_weights(self, grad:np.ndarray, lr:float) -> np.ndarray:
    return (self.w - lr*grad)

  def gd(self, X:np.ndarray, y:np.ndarray,
         num_epochs:int, lr:float, reg_rate:float) -> np.ndarray:
    self.w = np.zeros(X.shape[1])
    self.w_all = []
    self.err_all = []
    for i in np.arange(0, num_epochs):
      dJdw = self.calculate_gradient(X, y, reg_rate)
      self.w_all.append(self.w)
      self.err_all.append(self.loss(X, y, reg_rate))
      self.w = self.update_weights(dJdw, lr)
    return self.w

In [5]:
log_reg = LogisticRegression()

In [ ]:
z = X @ w
z

array([0.5, 0.7])

In [ ]:
sig = 1/(1+np.exp(-z))
sig

array([0.62245933, 0.66818777])

In [ ]:
loss_grad = np.transpose(X) @ (sig - y)
loss_grad

array([0.2906471 , 1.24948198])

# Q7 GA5

In [ ]:
yt = np.array([ 1, 0, 0, 1, 0, 0, 0, 1, 1 ])
predicted_prob = np.array([0.9,0.3,0.25,0.88,0.1,0.1,0.6,0.9,0.75])
-1 * (np.sum(yt * np.log(predicted_prob) + (1-yt) * np.log(1-predicted_prob)))

2.397605254857639